server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /admin {
    return 301 /admin/;
  }

  location /admin/ {
    try_files $uri $uri/ /admin/index.html;
  }

  location = /portaria {
    return 301 /portaria/;
  }

  location /portaria/ {
    try_files $uri $uri/ /portaria/index.html;
  }

  location = /pesquisa {
    return 301 /pesquisa/;
  }

  location /pesquisa/ {
    try_files $uri $uri/ /pesquisa/index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}